#!/usr/bin/env bash

set -euo pipefail

scriptDir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "${scriptDir}"

# Build the docker image.
# The use of tar is a workaround for the docker restriction of not following symlinks.  Originally
# we used to pass this directly into the docker build command but it can't handle the tar format
# generated by the BSD tar included with OSX.  Instead we create a temporary folder with the
# untarred contents and pass that instead.
rm -rf tmp-context
mkdir -p tmp-context
tar -czh . | tar -C tmp-context -zx -
docker build -t="openstreetmap.org/osmosis-db" tmp-context
rm -rf tmp-context
